if(NOT DEFINED TEST_EXECUTABLE)
    message(FATAL_ERROR "TEST_EXECUTABLE is required")
endif()

if(NOT DEFINED WORKING_DIRECTORY)
    message(FATAL_ERROR "WORKING_DIRECTORY is required")
endif()

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

execute_process(
    COMMAND "${TEST_EXECUTABLE}" --list-cases
    WORKING_DIRECTORY "${WORKING_DIRECTORY}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error_output
)

if(NOT result EQUAL 0)
    message(FATAL_ERROR "Failed to discover tests: ${error_output}")
endif()

string(REPLACE "\r\n" "\n" output "${output}")
string(REPLACE "\n" ";" test_cases "${output}")

set(contents "# Generated by discover_memmy_tests.cmake\n")
foreach(test_case IN LISTS test_cases)
    if(NOT test_case STREQUAL "")
        string(APPEND contents "add_test([=[${test_case}]=] [=[${TEST_EXECUTABLE}]=] --case [=[${test_case}]=])\n")
        string(APPEND contents "set_tests_properties([=[${test_case}]=] PROPERTIES WORKING_DIRECTORY [=[${WORKING_DIRECTORY}]=])\n")
    endif()
endforeach()

file(WRITE "${OUTPUT_FILE}" "${contents}")
